---
name: Link checker finds and reports broken links

on:
  workflow_dispatch

jobs:
  checker:
    runs-on: ubuntu-latest
    steps:
      - name: run checker in node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - run: npx broken-link-checker https://learn.madetech.com --exclude microsoft --exclude linkedin --exclude twitter --exclude codewars.com -ro