---
name: Link checker hunts broken links

# on:
#   workflow_dispatch

on:
  schedule:
    - cron: "24 17 * * 6"

jobs:
  checker:
    runs-on: ubuntu-latest
    steps:
      - name: set up node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Ensure no broken links
        run: npx broken-link-checker https://learn.madetech.com --exclude microsoft --exclude linkedin --exclude twitter --exclude codewars.com -ro